lera_project/competitions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.competition_list_view, name='competition_list'),
    url(r'^(?P<competition_id>[0-9]+)/create-member/$', views.create_competition_member,
        name='create-competition-member'),
    url(r'^(?P<competition_id>[0-9]+)/members/$', views.competition_member_list_view,
        name='member_list'),
]

lera_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from general import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home-page'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^create_user/$', views.create_user, name='create-user'),
    url(r'^competition/',  include('lera_project.competitions.urls', namespace='competition')),
    url(r'^trainer/',  include('lera_project.trainers.urls', namespace='trainer')),
    url(r'^training/',  include('lera_project.trainings.urls', namespace='training')),

]

lera_project/competitions/models.py
from __future__ import unicode_literals
from datetime import date

from django.utils.translation import ugettext_lazy as _
from django.db import models

from lera_project.trainers.models import Trainer


class Competition(models.Model):
    date = models.DateField()
    time = models.TimeField()
    description = models.TextField()
    title = models.CharField(max_length=255, null=True, blank=True)
    place = models.CharField(max_length=255)

    def __str__(self):
        return '({} {}) {}'.format(self.date, self.time, self.title)


class CompetitionMember(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, _('Male')),
        (FEMALE, _('Female'))
    )
    competition = models.ForeignKey(Competition)
    name = models.CharField(max_length=255)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name=_('Gender'))
    sport_category = models.CharField(max_length=255, choices=Trainer.CATEGORY_CHOICES)
    date_birth = models.DateField(help_text="Format XXXX-XX-XX")
    trainer = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    sport_club = models.CharField(max_length=255, null=True, blank=True)
    phone_first = models.CharField(max_length=14, )

    def calculate_age(self):
        if self.date_birth:
            today = date.today()
            return today.year - self.date_birth.year - (
                (today.month, today.day) < (self.date_birth.month,
                                            self.date_birth.day))
        return False

lera_project/competitions/forms.py
from django.forms.models import ModelForm

from .models import CompetitionMember
from lera_project.general.forms import CustomFormMixin


class CompetitionMemberForm(CustomFormMixin, ModelForm):
    class Meta:
        model = CompetitionMember
        exclude = ['competition']

lera_project/competitions/views.py
from django.http.response import HttpResponseRedirect, HttpResponseNotFound
from django.utils.timezone import datetime
from django.core.urlresolvers import reverse
from django.shortcuts import render

from .forms import CompetitionMemberForm
from .models import Competition, CompetitionMember


def competition_list_view(request):
    competitions = Competition.objects.filter(date__gte=datetime.today().date())
    return render(request, 'competition/competition_list.html', {'competitions': competitions})


def create_competition_member(request, competition_id):
    if Competition.objects.filter(pk=competition_id).exists():
        competition = Competition.objects.get(pk=competition_id)
    else:
        return HttpResponseNotFound('<h1>No competition matching your query</h1>')

    if request.method == 'POST':
        form = CompetitionMemberForm(request.POST)
        if form.is_valid():
            member = form.save(commit=False)
            member.competition = competition
            member.save()
            return HttpResponseRedirect(reverse('competition:competition_list'))
    else:
        form = CompetitionMemberForm()
    return render(request, 'competition/create_member.html', {'form': form, 'competition': competition})


def competition_member_list_view(request, competition_id):
    member_list = CompetitionMember.objects.filter(competition=competition_id)
    return render(request, 'competition/member_list.html', {"member_list": member_list})

templates/competition/competition_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Competitions {% endblock %}

{% block breadcrumbs %}
  <li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="{% url 'home-page' %}">Home</a>
  </li>
  <li>
    <span>Competitions</span>
  </li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <table id="simple-table" class="table  table-bordered table-hover">
        <thead>
        <tr>
          <th>Details</th>
          <th>Title</th>
          <th>Time</th>
          <th>Place</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        {% for competition in competitions %}
          <tr>
            <td class="center">
              <div class="action-buttons">
                <a href="#" class="green bigger-140 show-details-btn" title="Show Details">
                  <i class="ace-icon fa fa-angle-double-down"></i>
                  <span class="sr-only">Details</span>
                </a>
              </div>
            </td>
            <td>
              <h5>{{ competition.title }}</h5>
            </td>
            <td><h5>{{ competition.date }} {{ competition.time }}</h5></td>
            <td><h5>{{ competition.place }}</h5></td>
            <td>
              <a href="{% url 'competition:member_list' competition.id %}" class="  btn-xs btn btn-default">
                <h6>Members list</h6>
              </a>
            </td>
            <td>
              <a href="{% url 'competition:create-competition-member' competition.id %}" class="  btn-xs btn btn-success{% if not request.user.is_authenticated %} disabled {% endif %}">
                <h6>Take part</h6>
              </a>
            </td>
          </tr>
          <tr class="detail-row">
            <td colspan="8">
              <h4>{{ competition.description }}</h4>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div><!-- /.span -->
  </div><!-- /.row -->
{% endblock content %}
{% block extrascripts %}

  <script src="{% static 'js/table.js' %}"></script>

{% endblock %}

templates/competition/create_member.html
{% extends "base.html" %}
{% load static %}

{% block title %} Create member {% endblock %}

{% block breadcrumbs %}
  <li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="{% url 'home-page' %}">Home</a>
  </li>
  <li>
    <a href="{% url 'competition:competition_list' %}">Competitions</a>
  </li>
  <li>
    <span>Заявка на участие</span>
  </li>
{% endblock %}
{% block content %}
  <form role="form" action="{% url 'competition:create-competition-member' competition.id %}" class="form-horizontal" method="post">
    {% for field in form %}
      <div class="form-group {% if form.errors %} has-error {% endif %}">
        <label class="col-sm-3 control-label no-padding-right">{{ field.label_tag }}</label>
        <div class="col-sm-9">
          {{ field }}
          <div style='margin-left: 15px' class="help-block col-xs-12 col-sm-reset inline">
            {% for e in field.errors %}
              {{ e }}
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <div class="clearfix">
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-success">Sign up</button>
        <button type="submit" class="btn ">Cancel</button>
      </div>
    </div>
  </form>
{% endblock content %}

templates/competition/member_list.html
{% extends "base.html" %}
{% load static %}

{% block title %} Member-list {% endblock %}

{% block breadcrumbs %}
  <li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="{% url 'home-page' %}">Home</a>
  </li>
  <li>
    <a href="{% url 'competition:competition_list' %}">Competitions</a>
  </li>
  <li>
    <span>Members</span>
  </li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      {% if member_list %}
        <table id="simple-table" class="table  table-bordered table-hover">
          <thead>
          <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Sport category</th>
            <th>Age</th>
            <th>Trainer</th>
            <th>City</th>
            <th>Sport club</th>
            <th>Phone</th>
          </tr>
          </thead>
          <tbody>
          {% for member in member_list %}
            <tr>
              <td><h5>{{ member.name }}</h5></td>
              <td><h5>{{ member.gender }}</h5></td>
              <td><h5>{{ member.sport_category }}</h5></td>
              <td><h5>{{ member.calculate_age }}</h5></td>
              <td><h5>{{ member.trainer }}</h5></td>
              <td><h5>{{ member.city }}</h5></td>
              <td><h5>{{ member.sport_club }}</h5></td>
              <td><h5>{{ member.phone_first }}</h5></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      {% else %}
        <div class="page-header"><h1>Nobody still has registered</h1></div>
      {% endif %}
    </div><!-- /.span -->
  </div><!-- /.row -->
{% endblock content %}
{% block extrascripts %}

  <script src="{% static 'js/table.js' %}"></script>

{% endblock %}