lera_project/competitions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.competition_list_view, name='competition_list'),
    url(r'^(?P<competition_id>[0-9]+)/create-member/$', views.create_competition_member,
        name='create-competition-member'),
    url(r'^(?P<competition_id>[0-9]+)/members/$', views.competition_member_list_view,
        name='member_list'),
]

lera_project/trainings/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.training_index_view, name='index'),
    url(r'^(?P<training_id>[0-9]+)/member/add/$', views.training_member_add_view, name='member_add'),
    url(r'^(?P<training_id>[0-9]+)/member/list/$', views.training_member_list_view, name='member_list'),

]

lera_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from general import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home-page'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^create_user/$', views.create_user, name='create-user'),
    url(r'^competition/',  include('lera_project.competitions.urls', namespace='competition')),
    url(r'^trainer/',  include('lera_project.trainers.urls', namespace='trainer')),
    url(r'^training/',  include('lera_project.trainings.urls', namespace='training')),

]

lera_project/trainings/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.core.exceptions import ValidationError
from lera_project.trainers.models import Trainer


class Training(models.Model):
    LOW_SKILLED = 'Low skilled'
    MIDDLE_SKILLED = 'Middle skilled'
    HIGH_SKILLED = 'High skilled'
    CATEGORY_CHOICES = (
        (LOW_SKILLED, _('Low skilled')),
        (MIDDLE_SKILLED, _('Middle skilled')),
        (HIGH_SKILLED, _('High skilled'))
    )
    KIDS = 'Kids'
    ADULTS = 'Adults'
    GROUP_CHOICES = (
        (KIDS, _('Kids')),
        (ADULTS, _('Adults')),
    )
    MONDAY = 'Monday'
    TUESDAY = 'Tuesday'
    WEDNESDAY = 'Wednesday'
    THURSDAY = 'Tuesday'
    FRIDAY = 'Friday'
    SATURDAY = 'Saturday'
    SUNDAY = 'Sandy'
    DAY_CHOICES = (
        (MONDAY, _('Monday')),
        (TUESDAY, _('Tuesday')),
        (WEDNESDAY, _('Wednesday')),
        (THURSDAY, _('Tuesday')),
        (FRIDAY, _('Friday')),
        (SATURDAY, _('Saturday')),
        (SUNDAY, _('Sandy')),
    )
    FIRST = '14-16'
    SECOND = '16-18'
    THIRD = '18-20'
    FORTH = '20-22'
    TIME_CHOICES = (
        (FIRST, '14-16'),
        (SECOND, '16-18'),
        (THIRD, '18-20'),
        (FORTH, '20-22')
    )
    day = models.CharField(max_length=255, choices=DAY_CHOICES)
    time = models.CharField(max_length=6, choices=TIME_CHOICES)
    category = models.CharField(max_length=255, choices=CATEGORY_CHOICES)
    group = models.CharField(max_length=255, choices=GROUP_CHOICES)
    trainer = models.ForeignKey(Trainer)

    def __str__(self):
        return '{}  {}'.format(self.time, self.day)
    # def save(self, *args, **kwargs):
    #     if Training.objects.filter(day=self.day, time=self.time).exists():
    #         return ValidationError("Sprint is incorrect")

lera_project/trainings/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect

from lera_project.trainings.models import Training


def training_index_view(request):
    trainings = Training.objects.all()
    res = {'Monday': ['', '', '', ''], 'Tuesday': ['', '', '', ''], 'Wednesday': ['', '', '', ''],
           'Thursday': ['', '', '', ''], 'Friday': ['', '', '', ''],
           'Saturday': ['', '', '', ''], 'Sunday': ['', '', '', '']}
    for training in trainings:
        if training.time == '14-16':
            res[training.day][0] = training
        if training.time == '16-18':
            res[training.day][1] = training
        if training.time == '18-20':
            res[training.day][2] = training
        if training.time == '20-22':
            res[training.day][3] = training
    return render(request, 'training.html', {'res': res})


def training_member_add_view(request, training_id):
    training = get_object_or_404(Training, pk=training_id)
    training.member.add(request.user)
    return redirect('training:index')


def training_member_list_view(request, training_id):
    training = get_object_or_404(Training, pk=training_id)
    members = User.objects.filter(training=training)
    return render(request, 'training/training_list.html', {'member_list': members})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta charset="utf-8"/>

  <meta name="description" content="Common UI Features &amp; Elements"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
  <title>Format-club | {% block title %} {% endblock %}</title>

  {% block favicon %}
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>
  {% endblock %}

  {# Block where global CSS will go. #}
  {% block styles %}
    <style>
      html, body { height: 100%; margin: 0; padding: 0; }
      /* some elements used in demo only */
      .spinner-preview {
        width: 100px;
        height: 100px;
        text-align: center;
        margin-top: 60px;
      }

      .dropdown-preview {
        margin: 0 5px;
        display: inline-block;
      }

      .dropdown-preview > .dropdown-menu {
        display: block;
        position: static;
        margin-bottom: 5px;
      }

    </style>
    {#custom styles#}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href='{% static 'css/bootstrap.css' %}' type='text/css'/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type='text/css'/>

    <!-- page specific plugin styles -->

    <!-- text fonts -->
    <link rel="stylesheet" href="{% static 'css/ace-fonts.css' %}" type='text/css'/>

    <!-- ace styles -->
    <link href='{% static "css/ace.css" %}' rel='stylesheet' type='text/css' class="ace-main-stylesheet"
          id="main-ace-style"/>
  {% endblock %}

  {# Additional CSS - specific to certain pages #}
  {% block extrastyles %}{% endblock %}
</head>

<body class="no-skin">
<!-- #section:basics/navbar.layout -->
<div id="navbar" class="navbar navbar-default          ace-save-state">
  <div class="navbar-container ace-save-state" id="navbar-container">
    <!-- #section:basics/sidebar.mobile.toggle -->
    <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
      <span class="sr-only">Toggle sidebar</span>

      <span class="icon-bar"></span>

      <span class="icon-bar"></span>

      <span class="icon-bar"></span>
    </button>

    <!-- /section:basics/sidebar.mobile.toggle -->
    <div class="navbar-header pull-left">
      <!-- #section:basics/navbar.layout.brand -->
      <a href="{% url 'home-page' %}" class="navbar-brand">
        <img style="height: 50px;width: 195px;" src="{% static 'img/logo.png' %}" alt="">
      </a>
    </div>

    <!-- #section:basics/navbar.dropdown -->
    <div class="navbar-buttons navbar-header pull-right" role="navigation">
      <ul class="nav ace-nav">

        <!-- #section:basics/navbar.user_menu -->
        {% if request.user.is_authenticated %}
          <li class="light-blue">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle">
              <span class="user-info"><small>Welcome,</small>
                {{ request.user }}</span>
              <i class="ace-icon fa fa-caret-down"></i>
            </a>

            <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
              <li>
                <a href="{% url 'logout' %}">
                  <i class="ace-icon fa fa-power-off"></i>
                  Logout
                </a>
              </li>
            </ul>
          </li>
        {% else %}
          <li class="light-blue">
            <a href="{% url 'create-user' %}">Registration</a>
          </li>
          <li class="light-blue">
            <a href="{% url 'login' %}">Login</a>
          </li>

        {% endif %}
        <!-- /section:basics/navbar.user_menu -->
      </ul>
    </div>

    <!-- /section:basics/navbar.dropdown -->
  </div><!-- /.navbar-container -->
</div>

<!-- /section:basics/navbar.layout -->
<div class="main-container ace-save-state" id="main-container">
  <script type="text/javascript">
    try {
      ace.settings.loadState('main-container')
    } catch (e) {
    }
  </script>

  <!-- #section:basics/sidebar -->
  <div id="sidebar" class="sidebar                  responsive                    ace-save-state">
    <script type="text/javascript">
      try {
        ace.settings.loadState('sidebar')
      } catch (e) {
      }
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
      <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
        <button class="btn btn-success">
          <i class="ace-icon fa fa-signal"></i>
        </button>

        <button class="btn btn-info">
          <i class="ace-icon fa fa-pencil"></i>
        </button>

        <!-- #section:basics/sidebar.layout.shortcuts -->
        <button class="btn btn-warning">
          <i class="ace-icon fa fa-users"></i>
        </button>

        <button class="btn btn-danger">
          <i class="ace-icon fa fa-cogs"></i>
        </button>

        <!-- /section:basics/sidebar.layout.shortcuts -->
      </div>

      <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
        <span class="btn btn-success"></span>

        <span class="btn btn-info"></span>

        <span class="btn btn-warning"></span>

        <span class="btn btn-danger"></span>
      </div>
    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
      <li class="">
        <a href="{% url 'training:index' %}">
          <i class="menu-icon"> <span class="glyphicon glyphicon-file"></span></i>
          <span class="menu-text"> Training list </span>
        </a>

        <b class="arrow"></b>
      </li>
      <li class="">
        <a href="{% url 'trainer:index' %}">
          <i class="menu-icon"><span class="glyphicon glyphicon-star"></span></i>
          <span class="menu-text"> Our trainers </span>
        </a>

        <b class="arrow"></b>
      </li>
      <li class="">
        <a href="{% url 'competition:competition_list' %}">
          <i class="menu-icon"><span class="glyphicon glyphicon-flag"></span></i>
          <span class="menu-text"> Future events </span>
        </a>

        <b class="arrow"></b>
      </li>
    </ul><!-- /.nav-list -->

    <!-- #section:basics/sidebar.layout.minimize -->
    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
      <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
         data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>

    <!-- /section:basics/sidebar.layout.minimize -->
  </div>

  <!-- /section:basics/sidebar -->
  <div class="main-content">
    <div class="main-content-inner">
      <!-- #section:basics/content.breadcrumbs -->

      <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
          {% block breadcrumbs %}
          {% endblock %}
        </ul><!-- /.breadcrumb -->

        <!-- #section:basics/content.searchbox -->
        <div class="nav-search" id="nav-search">
          <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input"
                         autocomplete="off"/>
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
          </form>
        </div><!-- /.nav-search -->

        <!-- /section:basics/content.searchbox -->
      </div>

      <!-- /section:basics/content.breadcrumbs -->
      <div class="page-content">
        <div class="row">
          <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            {% block content %}{% endblock %}
            <!-- PAGE CONTENT ENDS -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.page-content -->
    </div>
  </div><!-- /.main-content -->

  <div class="footer">
    <div class="footer-inner">
      <!-- #section:basics/footer -->
      <div class="footer-content">
						<span class="bigger-120">
							Format bouldering club 2013-2017
						</span>

        &nbsp; &nbsp;
        <span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
      </div>

      <!-- /section:basics/footer -->
    </div>
  </div>

  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
    <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
  </a>
</div><!-- /.main-container -->


{# Local scripts #}
{% block scripts %}
  <!-- basic scripts -->

  <!--[if !IE]> -->
  <script src="../static/js/jquery.js"></script>

  <!-- <![endif]-->

  <!--[if IE]>
<script src="../assets/js/jquery1x.js"></script>
<![endif]-->
  <script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='../assets/js/jquery.mobile.custom.js'>" + "<" + "/script>");
  </script>
  <script src="../static/js/bootstrap.js"></script>

  <!-- page specific plugin scripts -->

  <!-- ace scripts -->
  <script src="../static/js/ace/elements.scroller.js"></script>
  <script src="../static/js/ace/elements.colorpicker.js"></script>
  <script src="../static/js/ace/elements.fileinput.js"></script>
  <script src="../static/js/ace/elements.typeahead.js"></script>
  <script src="../static/js/ace/elements.wysiwyg.js"></script>
  <script src="../static/js/ace/elements.spinner.js"></script>
  <script src="../static/js/ace/elements.treeview.js"></script>
  <script src="../static/js/ace/elements.wizard.js"></script>
  <script src="../static/js/ace/elements.aside.js"></script>
  <script src="../static/js/ace/ace.js"></script>
  <script src="../static/js/ace/ace.ajax-content.js"></script>
  <script src="../static/js/ace/ace.touch-drag.js"></script>
  <script src="../static/js/ace/ace.sidebar.js"></script>
  <script src="../static/js/ace/ace.sidebar-scroll-1.js"></script>
  <script src="../static/js/ace/ace.submenu-hover.js"></script>
  <script src="../static/js/ace/ace.widget-box.js"></script>
  <script src="../static/js/ace/ace.settings.js"></script>
  <script src="../static/js/ace/ace.settings-rtl.js"></script>
  <script src="../static/js/ace/ace.settings-skin.js"></script>
  <script src="../static/js/ace/ace.widget-on-reload.js"></script>
  <script src="../static/js/ace/ace.searchbox-autocomplete.js"></script>

  <!-- inline scripts related to this page -->

  <!-- the following scripts are used in demo only for onpage help and you don't need them -->
  <link rel="stylesheet" href="../static/css/ace.onpage-help.css"/>

  <script type="text/javascript"> ace.vars['base'] = '..'; </script>
  <script src="../static/js/ace/elements.onpage-help.js"></script>
  <script src="../static/js/ace/ace.onpage-help.js"></script>

{% endblock %}

{# Additional JS scripts #}
{% block extrascripts %}{% endblock %}
</body>
</html>

templates/create_user.html
{% extends "base.html" %}
{% load static %}

{% block title %} Registration {% endblock %}

{% block breadcrumbs %}
  <li>
    <p>Login</p>
  </li>

{% endblock %}

{% block content %}
  <form role="form" action="{% url 'create-user' %}" class="form-horizontal" method="post">
    {% for field in form %}
      <div class="form-group {% if form.errors %} has-error {% endif %}">
      <label class="col-sm-3 control-label no-padding-right">{{ field.label_tag }}</label>
      <div class="col-sm-9">
        {{ field }}
        <div class="help-block col-xs-12 col-sm-reset inline">
          {% for e in field.errors %}
            {{ e }}
          {% endfor %}
        </div>
      </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <div class="clearfix">
    <div class="col-sm-offset-3 col-sm-9">
      <button type="submit" class="btn btn-success">Sign up</button>
      <button type="submit" class="btn ">Cancel</button>
    </div>
  </div>
  </form>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} Home {% endblock %}

{% block breadcrumbs %}
  <li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="{% url 'home-page' %}">Home</a>
  </li>

{% endblock %}

{% block content %}
  <div class="text-center">
    <h2>Hello! You have visited site of bouldering club FORMAT</h2>
  </div>

  <h3><div class='leftimg' id="map-canvas" style="height: 200px; width: 400px;"></div>{{ info.club_description }}</h3>
  <h4>You can find us on {{ info.address }}</h4>
  <h4>Phone: {{ info.phone_first }} или {{ info.phone_second }}</h4>
  <h4>Email: {{ info.email }}</h4>


{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript"
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhJYRfwk0ftCU6ygdGtcBDJbSZzMBGfpA&sensor=false">
  </script>
  <script type="text/javascript">
    function initialize() {
      var mapOptions = {
        center: new google.maps.LatLng({{ info.latitude }}, {{ info.longitude }}),
        zoom: 17,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map-canvas"),
          mapOptions);

      var marker = new google.maps.Marker({
        position: {lat: {{ info.latitude }}, lng: {{ info.longitude }}},
        map: map,
        title: 'Format club'
      });
    }
    google.maps.event.addDomListener(window, "load", initialize);
  </script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}

{% block title %} Login {% endblock %}

{% block breadcrumbs %}
  <li>
    <p>Login</p>
  </li>

{% endblock %}

{% block content %}
  <form role="form" class="form-horizontal" action="{% url 'login' %}" method="post">
    <div class="form-group {% if form.errors %} has-error {% endif %}">
      <label class="col-sm-3 control-label no-padding-right">{{ form.username.label_tag }}:</label>
      <div class="col-sm-9">{{ form.username }}
        <div class="help-block col-xs-12 col-sm-reset inline">
          {% for e in form.username.errors %}
            {{ e }}
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="form-group {% if form.errors %} has-error {% endif %}">
      <label class="col-sm-3 control-label no-padding-right">{{ form.password.label_tag }}:</label>
      <div class="col-sm-9">{{ form.password }}</div>
      <div class="help-block">
        {% for e in form.password.errors %}
          {{ e }}
        {% endfor %}
      </div>
    </div>
  <div class="clearfix">
    <div class="col-sm-offset-3 col-sm-9">
      <button type="submit" class="btn btn-success">Login</button>
      <button type="submit" class="btn ">Cancel</button>
    </div>
  </div>
    {% csrf_token %}
  </form>
{% endblock %}

templates/training.html
{% extends "base.html" %}
{% load static %}

{% block title %} Trainings {% endblock %}

{% block breadcrumbs %}
  <li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="{% url 'home-page' %}">Home</a>
  </li>
  <li>
    <span>Trainings</span>
  </li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <table id="simple-table" class="table training-table table-bordered table-hover">
        <tbody>
        {% for key, value in res.items %}
          <tr>
            <td class="table-day">{{ key }}</td>
            {% for i in value %}

              <td class="training-elem" {% if i.category == 'Low skilled' %}style="background-color: #ffb752"
                  {% elif i.category == 'Middle skilled' %}style="background-color: #6fb3e0"
                  {% elif i.category == 'High skilled' %}style="background-color: #87b87f"{% endif %}>
              {% if i %}
                <span>Category: {{ i.category }}</span><br>
                <span>Group: {{ i.group }}</span><br>
                <span>Trainer:</span><a href="{% url 'trainer:index' %}">{{ i.trainer.name }}</a><br>
                <a class="btn btn-xs btn-success" href="{% url 'training:member_add' i.id %}">Take part</a>
                <a class="btn btn-xs btn-purple" href="{% url 'training:member_list' i.id %}">Member list</a>
              </td>

              {% endif %}
            {% endfor %}

          </tr>
        {% endfor %}

        </tbody>
      </table>
    </div><!-- /.span -->
  </div><!-- /.row -->

{% endblock content %}